### ISSUE TITLE
Platform dependencies are removed

### ISSUE THREAD

**Issue by felixfbecker** [dependencies-io/actor-js-npm#36]
Certain dependencies like `fsevents` are only installed on macOS.
When dependencies.io updates the package-lock.json to update a dependency, it removes all these platform-dependent dependencies from package-lock.json, as it's running on Linux, which means the PRs cannot be merged.
This is fixed in [npm v5.6](https://github.com/npm/npm/releases/tag/v5.6.0), currently at `npm@next`, so I would propose to update to that for dependencies.io.

**Comment by felixfbecker** [comment]
This feature in 5.6 might also be interesting for you:

> f94fcbc50 #19160 Add --package-lock-only config option. This makes it so you can generate a target package-lock.json without performing a full install of node_modules.

**Comment by davegaeddert** [comment]
Thanks for the tip on platform dependencies. Somebody else pointed out some other similar kinds of issues that 5.6 fixes, so we should be using it now: https://github.com/dependencies-io/actor-js-npm/commit/78c4db30058846d1de1bd4aaa8cb8c2cef2cde95#diff-8ee2343978836a779dc9f8d6b794c3b2R1319

I'll definitely take a look at `--package-lock-only`!
