### ISSUE TITLE
PR creation fails in batch mode

### ISSUE THREAD

**Issue by Hypnosphi** [dependencies-io/actor-js-npm#40]
See https://app.dependencies.io/projects/github/JetBrains/ring-ui/builds/126

**Comment by davegaeddert** [comment]
@Hypnosphi I'll run another build after the current one finishes. I think this might have actually just been fixed in 95180f0d41a483c555d7b942a7b1de8b31f1b312 (https://github.com/shelljs/shelljs/releases/tag/v0.8.1).
