### ISSUE TITLE
Actor replaces caret versions with exact ones

### ISSUE THREAD

**Issue by Hypnosphi** [dependencies-io/actor-js-npm#5]
E.g.: https://github.com/Hypnosphi/storybook/pull/34/files

**Comment by davegaeddert** [comment]
@Hypnosphi I made a change around this to preserve the carets and tildes when using yarn (#6). The new version of this actor will be used the next time dependencies.io runs (tomorrow automatically). You can see an example of the new output here: https://github.com/davegaeddert/storybook/pull/62/files

Let me know if you have any questions.

**Comment by Hypnosphi** [comment]
I believe that can be useful for npm users as well

**Comment by davegaeddert** [comment]
At least at a glance, the newer versions of npm actually do it automatically, but I'll double check.
